#
# test-e3-skr13-tmc5160-bltouch-build.yml
# Do test build to catch compile errors
#

name: Ender-3 / SKR 1.3 / TMC5160s / BLTouch CI

on:
  pull_request:
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'
  push:
    paths-ignore:
    - config/**
    - data/**
    - docs/**
    - '**/*.md'

jobs:
  test_builds:
    name: Test Build
    if: github.repository == 'thisiskeithb/Marlin'

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Commit
      uses: actions/checkout@v4

    - name: Select Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        architecture: 'x64'

    - name: Install PlatformIO
      run: |
        pip install -U platformio
        pio upgrade --dev
        pio pkg update --global

    - name: Build Marlin
      run: pio run
